version:
	solc-select use 0.4.24

build:
	solc --bin store.sol -o build --overwrite
	solc --abi store.sol -o build --overwrite
	abigen --bin=build/store.bin --abi=build/store.abi --pkg=store --out=store/store.go



