version:
	solc-select use 0.4.24

build:
	solc --bin Store.sol -o build --overwrite
	solc --abi Store.sol -o build --overwrite
	abigen --bin=build/Store.bin --abi=build/Store.abi --pkg=store --out=store/Store.go



