// Code generated by entc, DO NOT EDIT.

package orderheader

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the orderheader type in the database.
	Label = "order_header"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldStringRef holds the string denoting the string_ref field in the database.
	FieldStringRef = "string_ref"
	// FieldOrderTypeID holds the string denoting the order_type_id field in the database.
	FieldOrderTypeID = "order_type_id"
	// FieldOrderName holds the string denoting the order_name field in the database.
	FieldOrderName = "order_name"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldOrderDate holds the string denoting the order_date field in the database.
	FieldOrderDate = "order_date"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldEntryDate holds the string denoting the entry_date field in the database.
	FieldEntryDate = "entry_date"
	// FieldPickSheetPrintedDate holds the string denoting the pick_sheet_printed_date field in the database.
	FieldPickSheetPrintedDate = "pick_sheet_printed_date"
	// FieldVisitID holds the string denoting the visit_id field in the database.
	FieldVisitID = "visit_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldFirstAttemptOrderID holds the string denoting the first_attempt_order_id field in the database.
	FieldFirstAttemptOrderID = "first_attempt_order_id"
	// FieldCurrencyUom holds the string denoting the currency_uom field in the database.
	FieldCurrencyUom = "currency_uom"
	// FieldBillingAccountID holds the string denoting the billing_account_id field in the database.
	FieldBillingAccountID = "billing_account_id"
	// FieldOriginFacilityID holds the string denoting the origin_facility_id field in the database.
	FieldOriginFacilityID = "origin_facility_id"
	// FieldWebSiteID holds the string denoting the web_site_id field in the database.
	FieldWebSiteID = "web_site_id"
	// FieldAgreementID holds the string denoting the agreement_id field in the database.
	FieldAgreementID = "agreement_id"
	// FieldTerminalID holds the string denoting the terminal_id field in the database.
	FieldTerminalID = "terminal_id"
	// FieldTransactionID holds the string denoting the transaction_id field in the database.
	FieldTransactionID = "transaction_id"
	// FieldAutoOrderShoppingListID holds the string denoting the auto_order_shopping_list_id field in the database.
	FieldAutoOrderShoppingListID = "auto_order_shopping_list_id"
	// FieldNeedsInventoryIssuance holds the string denoting the needs_inventory_issuance field in the database.
	FieldNeedsInventoryIssuance = "needs_inventory_issuance"
	// FieldIsRushOrder holds the string denoting the is_rush_order field in the database.
	FieldIsRushOrder = "is_rush_order"
	// FieldInternalCode holds the string denoting the internal_code field in the database.
	FieldInternalCode = "internal_code"
	// FieldRemainingSubTotal holds the string denoting the remaining_sub_total field in the database.
	FieldRemainingSubTotal = "remaining_sub_total"
	// FieldGrandTotal holds the string denoting the grand_total field in the database.
	FieldGrandTotal = "grand_total"
	// FieldIsViewed holds the string denoting the is_viewed field in the database.
	FieldIsViewed = "is_viewed"
	// FieldInvoicePerShipment holds the string denoting the invoice_per_shipment field in the database.
	FieldInvoicePerShipment = "invoice_per_shipment"
	// EdgeSalesChannelEnumeration holds the string denoting the sales_channel_enumeration edge name in mutations.
	EdgeSalesChannelEnumeration = "sales_channel_enumeration"
	// EdgeProductStore holds the string denoting the product_store edge name in mutations.
	EdgeProductStore = "product_store"
	// EdgeStatusItem holds the string denoting the status_item edge name in mutations.
	EdgeStatusItem = "status_item"
	// EdgeSyncStatusItem holds the string denoting the sync_status_item edge name in mutations.
	EdgeSyncStatusItem = "sync_status_item"
	// EdgeOrderAdjustments holds the string denoting the order_adjustments edge name in mutations.
	EdgeOrderAdjustments = "order_adjustments"
	// EdgeOrderContactMeches holds the string denoting the order_contact_meches edge name in mutations.
	EdgeOrderContactMeches = "order_contact_meches"
	// EdgeOrderItems holds the string denoting the order_items edge name in mutations.
	EdgeOrderItems = "order_items"
	// EdgeOrderItemShipGroups holds the string denoting the order_item_ship_groups edge name in mutations.
	EdgeOrderItemShipGroups = "order_item_ship_groups"
	// EdgeOrderItemShipGroupAssocs holds the string denoting the order_item_ship_group_assocs edge name in mutations.
	EdgeOrderItemShipGroupAssocs = "order_item_ship_group_assocs"
	// EdgeOrderItemShipGrpInvRes holds the string denoting the order_item_ship_grp_inv_res edge name in mutations.
	EdgeOrderItemShipGrpInvRes = "order_item_ship_grp_inv_res"
	// EdgeOrderPaymentPreferences holds the string denoting the order_payment_preferences edge name in mutations.
	EdgeOrderPaymentPreferences = "order_payment_preferences"
	// EdgeOrderRoles holds the string denoting the order_roles edge name in mutations.
	EdgeOrderRoles = "order_roles"
	// EdgeOrderStatuses holds the string denoting the order_statuses edge name in mutations.
	EdgeOrderStatuses = "order_statuses"
	// Table holds the table name of the orderheader in the database.
	Table = "order_headers"
	// SalesChannelEnumerationTable is the table the holds the sales_channel_enumeration relation/edge.
	SalesChannelEnumerationTable = "order_headers"
	// SalesChannelEnumerationInverseTable is the table name for the Enumeration entity.
	// It exists in this package in order to avoid circular dependency with the "enumeration" package.
	SalesChannelEnumerationInverseTable = "enumerations"
	// SalesChannelEnumerationColumn is the table column denoting the sales_channel_enumeration relation/edge.
	SalesChannelEnumerationColumn = "enumeration_sales_channel_order_headers"
	// ProductStoreTable is the table the holds the product_store relation/edge.
	ProductStoreTable = "order_headers"
	// ProductStoreInverseTable is the table name for the ProductStore entity.
	// It exists in this package in order to avoid circular dependency with the "productstore" package.
	ProductStoreInverseTable = "product_stores"
	// ProductStoreColumn is the table column denoting the product_store relation/edge.
	ProductStoreColumn = "product_store_order_headers"
	// StatusItemTable is the table the holds the status_item relation/edge.
	StatusItemTable = "order_headers"
	// StatusItemInverseTable is the table name for the StatusItem entity.
	// It exists in this package in order to avoid circular dependency with the "statusitem" package.
	StatusItemInverseTable = "status_items"
	// StatusItemColumn is the table column denoting the status_item relation/edge.
	StatusItemColumn = "status_item_order_headers"
	// SyncStatusItemTable is the table the holds the sync_status_item relation/edge.
	SyncStatusItemTable = "order_headers"
	// SyncStatusItemInverseTable is the table name for the StatusItem entity.
	// It exists in this package in order to avoid circular dependency with the "statusitem" package.
	SyncStatusItemInverseTable = "status_items"
	// SyncStatusItemColumn is the table column denoting the sync_status_item relation/edge.
	SyncStatusItemColumn = "status_item_sync_order_headers"
	// OrderAdjustmentsTable is the table the holds the order_adjustments relation/edge.
	OrderAdjustmentsTable = "order_adjustments"
	// OrderAdjustmentsInverseTable is the table name for the OrderAdjustment entity.
	// It exists in this package in order to avoid circular dependency with the "orderadjustment" package.
	OrderAdjustmentsInverseTable = "order_adjustments"
	// OrderAdjustmentsColumn is the table column denoting the order_adjustments relation/edge.
	OrderAdjustmentsColumn = "order_header_order_adjustments"
	// OrderContactMechesTable is the table the holds the order_contact_meches relation/edge.
	OrderContactMechesTable = "order_contact_meches"
	// OrderContactMechesInverseTable is the table name for the OrderContactMech entity.
	// It exists in this package in order to avoid circular dependency with the "ordercontactmech" package.
	OrderContactMechesInverseTable = "order_contact_meches"
	// OrderContactMechesColumn is the table column denoting the order_contact_meches relation/edge.
	OrderContactMechesColumn = "order_header_order_contact_meches"
	// OrderItemsTable is the table the holds the order_items relation/edge.
	OrderItemsTable = "order_items"
	// OrderItemsInverseTable is the table name for the OrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "orderitem" package.
	OrderItemsInverseTable = "order_items"
	// OrderItemsColumn is the table column denoting the order_items relation/edge.
	OrderItemsColumn = "order_header_order_items"
	// OrderItemShipGroupsTable is the table the holds the order_item_ship_groups relation/edge.
	OrderItemShipGroupsTable = "order_item_ship_groups"
	// OrderItemShipGroupsInverseTable is the table name for the OrderItemShipGroup entity.
	// It exists in this package in order to avoid circular dependency with the "orderitemshipgroup" package.
	OrderItemShipGroupsInverseTable = "order_item_ship_groups"
	// OrderItemShipGroupsColumn is the table column denoting the order_item_ship_groups relation/edge.
	OrderItemShipGroupsColumn = "order_header_order_item_ship_groups"
	// OrderItemShipGroupAssocsTable is the table the holds the order_item_ship_group_assocs relation/edge.
	OrderItemShipGroupAssocsTable = "order_item_ship_group_assocs"
	// OrderItemShipGroupAssocsInverseTable is the table name for the OrderItemShipGroupAssoc entity.
	// It exists in this package in order to avoid circular dependency with the "orderitemshipgroupassoc" package.
	OrderItemShipGroupAssocsInverseTable = "order_item_ship_group_assocs"
	// OrderItemShipGroupAssocsColumn is the table column denoting the order_item_ship_group_assocs relation/edge.
	OrderItemShipGroupAssocsColumn = "order_header_order_item_ship_group_assocs"
	// OrderItemShipGrpInvResTable is the table the holds the order_item_ship_grp_inv_res relation/edge.
	OrderItemShipGrpInvResTable = "order_item_ship_grp_inv_res"
	// OrderItemShipGrpInvResInverseTable is the table name for the OrderItemShipGrpInvRes entity.
	// It exists in this package in order to avoid circular dependency with the "orderitemshipgrpinvres" package.
	OrderItemShipGrpInvResInverseTable = "order_item_ship_grp_inv_res"
	// OrderItemShipGrpInvResColumn is the table column denoting the order_item_ship_grp_inv_res relation/edge.
	OrderItemShipGrpInvResColumn = "order_header_order_item_ship_grp_inv_res"
	// OrderPaymentPreferencesTable is the table the holds the order_payment_preferences relation/edge.
	OrderPaymentPreferencesTable = "order_payment_preferences"
	// OrderPaymentPreferencesInverseTable is the table name for the OrderPaymentPreference entity.
	// It exists in this package in order to avoid circular dependency with the "orderpaymentpreference" package.
	OrderPaymentPreferencesInverseTable = "order_payment_preferences"
	// OrderPaymentPreferencesColumn is the table column denoting the order_payment_preferences relation/edge.
	OrderPaymentPreferencesColumn = "order_header_order_payment_preferences"
	// OrderRolesTable is the table the holds the order_roles relation/edge.
	OrderRolesTable = "order_roles"
	// OrderRolesInverseTable is the table name for the OrderRole entity.
	// It exists in this package in order to avoid circular dependency with the "orderrole" package.
	OrderRolesInverseTable = "order_roles"
	// OrderRolesColumn is the table column denoting the order_roles relation/edge.
	OrderRolesColumn = "order_header_order_roles"
	// OrderStatusesTable is the table the holds the order_statuses relation/edge.
	OrderStatusesTable = "order_status"
	// OrderStatusesInverseTable is the table name for the OrderStatus entity.
	// It exists in this package in order to avoid circular dependency with the "orderstatus" package.
	OrderStatusesInverseTable = "order_status"
	// OrderStatusesColumn is the table column denoting the order_statuses relation/edge.
	OrderStatusesColumn = "order_header_order_statuses"
)

// Columns holds all SQL columns for orderheader fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldStringRef,
	FieldOrderTypeID,
	FieldOrderName,
	FieldExternalID,
	FieldOrderDate,
	FieldPriority,
	FieldEntryDate,
	FieldPickSheetPrintedDate,
	FieldVisitID,
	FieldCreatedBy,
	FieldFirstAttemptOrderID,
	FieldCurrencyUom,
	FieldBillingAccountID,
	FieldOriginFacilityID,
	FieldWebSiteID,
	FieldAgreementID,
	FieldTerminalID,
	FieldTransactionID,
	FieldAutoOrderShoppingListID,
	FieldNeedsInventoryIssuance,
	FieldIsRushOrder,
	FieldInternalCode,
	FieldRemainingSubTotal,
	FieldGrandTotal,
	FieldIsViewed,
	FieldInvoicePerShipment,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "order_headers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"enumeration_sales_channel_order_headers",
	"product_store_order_headers",
	"status_item_order_headers",
	"status_item_sync_order_headers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultOrderDate holds the default value on creation for the "order_date" field.
	DefaultOrderDate func() time.Time
	// DefaultEntryDate holds the default value on creation for the "entry_date" field.
	DefaultEntryDate func() time.Time
	// DefaultPickSheetPrintedDate holds the default value on creation for the "pick_sheet_printed_date" field.
	DefaultPickSheetPrintedDate func() time.Time
	// TerminalIDValidator is a validator for the "terminal_id" field. It is called by the builders before save.
	TerminalIDValidator func(string) error
	// TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	TransactionIDValidator func(string) error
	// InternalCodeValidator is a validator for the "internal_code" field. It is called by the builders before save.
	InternalCodeValidator func(string) error
)

// Priority defines the type for the "priority" enum field.
type Priority string

// Priority values.
const (
	PriorityYes     Priority = "Yes"
	PriorityNo      Priority = "No"
	PriorityUnknown Priority = "Unknown"
)

func (pr Priority) String() string {
	return string(pr)
}

// PriorityValidator is a validator for the "priority" field enum values. It is called by the builders before save.
func PriorityValidator(pr Priority) error {
	switch pr {
	case PriorityYes, PriorityNo, PriorityUnknown:
		return nil
	default:
		return fmt.Errorf("orderheader: invalid enum value for priority field: %q", pr)
	}
}

// NeedsInventoryIssuance defines the type for the "needs_inventory_issuance" enum field.
type NeedsInventoryIssuance string

// NeedsInventoryIssuance values.
const (
	NeedsInventoryIssuanceYes     NeedsInventoryIssuance = "Yes"
	NeedsInventoryIssuanceNo      NeedsInventoryIssuance = "No"
	NeedsInventoryIssuanceUnknown NeedsInventoryIssuance = "Unknown"
)

func (nii NeedsInventoryIssuance) String() string {
	return string(nii)
}

// NeedsInventoryIssuanceValidator is a validator for the "needs_inventory_issuance" field enum values. It is called by the builders before save.
func NeedsInventoryIssuanceValidator(nii NeedsInventoryIssuance) error {
	switch nii {
	case NeedsInventoryIssuanceYes, NeedsInventoryIssuanceNo, NeedsInventoryIssuanceUnknown:
		return nil
	default:
		return fmt.Errorf("orderheader: invalid enum value for needs_inventory_issuance field: %q", nii)
	}
}

// IsRushOrder defines the type for the "is_rush_order" enum field.
type IsRushOrder string

// IsRushOrder values.
const (
	IsRushOrderYes     IsRushOrder = "Yes"
	IsRushOrderNo      IsRushOrder = "No"
	IsRushOrderUnknown IsRushOrder = "Unknown"
)

func (iro IsRushOrder) String() string {
	return string(iro)
}

// IsRushOrderValidator is a validator for the "is_rush_order" field enum values. It is called by the builders before save.
func IsRushOrderValidator(iro IsRushOrder) error {
	switch iro {
	case IsRushOrderYes, IsRushOrderNo, IsRushOrderUnknown:
		return nil
	default:
		return fmt.Errorf("orderheader: invalid enum value for is_rush_order field: %q", iro)
	}
}

// IsViewed defines the type for the "is_viewed" enum field.
type IsViewed string

// IsViewed values.
const (
	IsViewedYes     IsViewed = "Yes"
	IsViewedNo      IsViewed = "No"
	IsViewedUnknown IsViewed = "Unknown"
)

func (iv IsViewed) String() string {
	return string(iv)
}

// IsViewedValidator is a validator for the "is_viewed" field enum values. It is called by the builders before save.
func IsViewedValidator(iv IsViewed) error {
	switch iv {
	case IsViewedYes, IsViewedNo, IsViewedUnknown:
		return nil
	default:
		return fmt.Errorf("orderheader: invalid enum value for is_viewed field: %q", iv)
	}
}

// InvoicePerShipment defines the type for the "invoice_per_shipment" enum field.
type InvoicePerShipment string

// InvoicePerShipment values.
const (
	InvoicePerShipmentYes     InvoicePerShipment = "Yes"
	InvoicePerShipmentNo      InvoicePerShipment = "No"
	InvoicePerShipmentUnknown InvoicePerShipment = "Unknown"
)

func (ips InvoicePerShipment) String() string {
	return string(ips)
}

// InvoicePerShipmentValidator is a validator for the "invoice_per_shipment" field enum values. It is called by the builders before save.
func InvoicePerShipmentValidator(ips InvoicePerShipment) error {
	switch ips {
	case InvoicePerShipmentYes, InvoicePerShipmentNo, InvoicePerShipmentUnknown:
		return nil
	default:
		return fmt.Errorf("orderheader: invalid enum value for invoice_per_shipment field: %q", ips)
	}
}
