gen:
	go generate
gen-example:
    python meta_generator.py abi [Example,ExampleItem]
gen-workload:
	python meta_generator.py gen_package "com.bluecc.workload" workload
gen-workload-ent:
	go test -run TestWriteSchemas
	go generate ./modules/workload/ent

# $ just schema workload
schema pkg:
	go run entgo.io/ent/cmd/ent describe ./modules/{{pkg}}/ent/schema

repl:
	ipython --profile=bluecc
backend:
	python backend.py

procs:
	foreman start

# $ just gencase purchaseorder
# $ just gencase workeffort
gencase modname:
    python meta_generator.py gen_case ./assets/cases/{{modname}}
    mage CreateMod {{modname}}
    mage WriteSchemas {{modname}}

onlygen mod:
    mage OnlyWriteSchemas {{mod}}

cli +FLAGS='':
    go run cli/main.go {{FLAGS}} || true

fmt pkg:
	go fmt modules/{{pkg}}/seedcreators/*.go

# generate creators and updaters
seed-gen pkg:
	go run cli/main.go seed-gen {{pkg}}
	go fmt modules/{{pkg}}/seedcreators/*.go

secas srv:
	python -m sagas.ofbiz.secas get_secas {{srv}} json

