gen-example:
    python meta_generator.py abi [Example,ExampleItem]
gen-workload:
	python meta_generator.py gen_package "com.bluecc.workload" workload
gen-workload-ent:
	go test -run TestWriteSchemas
	go generate ./modules/workload/ent

# $ just schema workload
schema pkg:
	go run entgo.io/ent/cmd/ent describe ./modules/{{pkg}}/ent/schema

repl:
	ipython --profile=bluecc
