// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/facilitytype"
)

// FacilityTypeCreate is the builder for creating a FacilityType entity.
type FacilityTypeCreate struct {
	config
	mutation *FacilityTypeMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ftc *FacilityTypeCreate) SetCreateTime(t time.Time) *FacilityTypeCreate {
	ftc.mutation.SetCreateTime(t)
	return ftc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ftc *FacilityTypeCreate) SetNillableCreateTime(t *time.Time) *FacilityTypeCreate {
	if t != nil {
		ftc.SetCreateTime(*t)
	}
	return ftc
}

// SetUpdateTime sets the "update_time" field.
func (ftc *FacilityTypeCreate) SetUpdateTime(t time.Time) *FacilityTypeCreate {
	ftc.mutation.SetUpdateTime(t)
	return ftc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ftc *FacilityTypeCreate) SetNillableUpdateTime(t *time.Time) *FacilityTypeCreate {
	if t != nil {
		ftc.SetUpdateTime(*t)
	}
	return ftc
}

// SetStringRef sets the "string_ref" field.
func (ftc *FacilityTypeCreate) SetStringRef(s string) *FacilityTypeCreate {
	ftc.mutation.SetStringRef(s)
	return ftc
}

// SetNillableStringRef sets the "string_ref" field if the given value is not nil.
func (ftc *FacilityTypeCreate) SetNillableStringRef(s *string) *FacilityTypeCreate {
	if s != nil {
		ftc.SetStringRef(*s)
	}
	return ftc
}

// SetHasTable sets the "has_table" field.
func (ftc *FacilityTypeCreate) SetHasTable(ft facilitytype.HasTable) *FacilityTypeCreate {
	ftc.mutation.SetHasTable(ft)
	return ftc
}

// SetNillableHasTable sets the "has_table" field if the given value is not nil.
func (ftc *FacilityTypeCreate) SetNillableHasTable(ft *facilitytype.HasTable) *FacilityTypeCreate {
	if ft != nil {
		ftc.SetHasTable(*ft)
	}
	return ftc
}

// SetDescription sets the "description" field.
func (ftc *FacilityTypeCreate) SetDescription(s string) *FacilityTypeCreate {
	ftc.mutation.SetDescription(s)
	return ftc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ftc *FacilityTypeCreate) SetNillableDescription(s *string) *FacilityTypeCreate {
	if s != nil {
		ftc.SetDescription(*s)
	}
	return ftc
}

// SetParentID sets the "parent" edge to the FacilityType entity by ID.
func (ftc *FacilityTypeCreate) SetParentID(id int) *FacilityTypeCreate {
	ftc.mutation.SetParentID(id)
	return ftc
}

// SetNillableParentID sets the "parent" edge to the FacilityType entity by ID if the given value is not nil.
func (ftc *FacilityTypeCreate) SetNillableParentID(id *int) *FacilityTypeCreate {
	if id != nil {
		ftc = ftc.SetParentID(*id)
	}
	return ftc
}

// SetParent sets the "parent" edge to the FacilityType entity.
func (ftc *FacilityTypeCreate) SetParent(f *FacilityType) *FacilityTypeCreate {
	return ftc.SetParentID(f.ID)
}

// AddChildIDs adds the "children" edge to the FacilityType entity by IDs.
func (ftc *FacilityTypeCreate) AddChildIDs(ids ...int) *FacilityTypeCreate {
	ftc.mutation.AddChildIDs(ids...)
	return ftc
}

// AddChildren adds the "children" edges to the FacilityType entity.
func (ftc *FacilityTypeCreate) AddChildren(f ...*FacilityType) *FacilityTypeCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return ftc.AddChildIDs(ids...)
}

// AddChildFacilityTypeIDs adds the "child_facility_types" edge to the FacilityType entity by IDs.
func (ftc *FacilityTypeCreate) AddChildFacilityTypeIDs(ids ...int) *FacilityTypeCreate {
	ftc.mutation.AddChildFacilityTypeIDs(ids...)
	return ftc
}

// AddChildFacilityTypes adds the "child_facility_types" edges to the FacilityType entity.
func (ftc *FacilityTypeCreate) AddChildFacilityTypes(f ...*FacilityType) *FacilityTypeCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return ftc.AddChildFacilityTypeIDs(ids...)
}

// Mutation returns the FacilityTypeMutation object of the builder.
func (ftc *FacilityTypeCreate) Mutation() *FacilityTypeMutation {
	return ftc.mutation
}

// Save creates the FacilityType in the database.
func (ftc *FacilityTypeCreate) Save(ctx context.Context) (*FacilityType, error) {
	var (
		err  error
		node *FacilityType
	)
	ftc.defaults()
	if len(ftc.hooks) == 0 {
		if err = ftc.check(); err != nil {
			return nil, err
		}
		node, err = ftc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FacilityTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ftc.check(); err != nil {
				return nil, err
			}
			ftc.mutation = mutation
			if node, err = ftc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ftc.hooks) - 1; i >= 0; i-- {
			mut = ftc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ftc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ftc *FacilityTypeCreate) SaveX(ctx context.Context) *FacilityType {
	v, err := ftc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (ftc *FacilityTypeCreate) defaults() {
	if _, ok := ftc.mutation.CreateTime(); !ok {
		v := facilitytype.DefaultCreateTime()
		ftc.mutation.SetCreateTime(v)
	}
	if _, ok := ftc.mutation.UpdateTime(); !ok {
		v := facilitytype.DefaultUpdateTime()
		ftc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ftc *FacilityTypeCreate) check() error {
	if _, ok := ftc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := ftc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if v, ok := ftc.mutation.HasTable(); ok {
		if err := facilitytype.HasTableValidator(v); err != nil {
			return &ValidationError{Name: "has_table", err: fmt.Errorf("ent: validator failed for field \"has_table\": %w", err)}
		}
	}
	return nil
}

func (ftc *FacilityTypeCreate) sqlSave(ctx context.Context) (*FacilityType, error) {
	_node, _spec := ftc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ftc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ftc *FacilityTypeCreate) createSpec() (*FacilityType, *sqlgraph.CreateSpec) {
	var (
		_node = &FacilityType{config: ftc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: facilitytype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: facilitytype.FieldID,
			},
		}
	)
	if value, ok := ftc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: facilitytype.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := ftc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: facilitytype.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := ftc.mutation.StringRef(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: facilitytype.FieldStringRef,
		})
		_node.StringRef = value
	}
	if value, ok := ftc.mutation.HasTable(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: facilitytype.FieldHasTable,
		})
		_node.HasTable = value
	}
	if value, ok := ftc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: facilitytype.FieldDescription,
		})
		_node.Description = value
	}
	if nodes := ftc.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   facilitytype.ParentTable,
			Columns: []string{facilitytype.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: facilitytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.facility_type_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ftc.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   facilitytype.ChildrenTable,
			Columns: []string{facilitytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: facilitytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ftc.mutation.ChildFacilityTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   facilitytype.ChildFacilityTypesTable,
			Columns: facilitytype.ChildFacilityTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: facilitytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FacilityTypeCreateBulk is the builder for creating many FacilityType entities in bulk.
type FacilityTypeCreateBulk struct {
	config
	builders []*FacilityTypeCreate
}

// Save creates the FacilityType entities in the database.
func (ftcb *FacilityTypeCreateBulk) Save(ctx context.Context) ([]*FacilityType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ftcb.builders))
	nodes := make([]*FacilityType, len(ftcb.builders))
	mutators := make([]Mutator, len(ftcb.builders))
	for i := range ftcb.builders {
		func(i int, root context.Context) {
			builder := ftcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FacilityTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ftcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ftcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ftcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ftcb *FacilityTypeCreateBulk) SaveX(ctx context.Context) []*FacilityType {
	v, err := ftcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
