// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/facilitytype"
)

// FacilityType is the model entity for the FacilityType schema.
type FacilityType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// StringRef holds the value of the "string_ref" field.
	StringRef string `json:"string_ref,omitempty"`
	// HasTable holds the value of the "has_table" field.
	HasTable facilitytype.HasTable `json:"has_table,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FacilityTypeQuery when eager-loading is set.
	Edges                  FacilityTypeEdges `json:"edges"`
	facility_type_children *int
}

// FacilityTypeEdges holds the relations/edges for other nodes in the graph.
type FacilityTypeEdges struct {
	// Parent holds the value of the parent edge.
	Parent *FacilityType `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*FacilityType `json:"children,omitempty"`
	// ChildFacilityTypes holds the value of the child_facility_types edge.
	ChildFacilityTypes []*FacilityType `json:"child_facility_types,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FacilityTypeEdges) ParentOrErr() (*FacilityType, error) {
	if e.loadedTypes[0] {
		if e.Parent == nil {
			// The edge parent was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: facilitytype.Label}
		}
		return e.Parent, nil
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e FacilityTypeEdges) ChildrenOrErr() ([]*FacilityType, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// ChildFacilityTypesOrErr returns the ChildFacilityTypes value or an error if the edge
// was not loaded in eager-loading.
func (e FacilityTypeEdges) ChildFacilityTypesOrErr() ([]*FacilityType, error) {
	if e.loadedTypes[2] {
		return e.ChildFacilityTypes, nil
	}
	return nil, &NotLoadedError{edge: "child_facility_types"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FacilityType) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case facilitytype.FieldID:
			values[i] = new(sql.NullInt64)
		case facilitytype.FieldStringRef, facilitytype.FieldHasTable, facilitytype.FieldDescription:
			values[i] = new(sql.NullString)
		case facilitytype.FieldCreateTime, facilitytype.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case facilitytype.ForeignKeys[0]: // facility_type_children
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type FacilityType", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FacilityType fields.
func (ft *FacilityType) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case facilitytype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ft.ID = int(value.Int64)
		case facilitytype.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ft.CreateTime = value.Time
			}
		case facilitytype.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ft.UpdateTime = value.Time
			}
		case facilitytype.FieldStringRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field string_ref", values[i])
			} else if value.Valid {
				ft.StringRef = value.String
			}
		case facilitytype.FieldHasTable:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field has_table", values[i])
			} else if value.Valid {
				ft.HasTable = facilitytype.HasTable(value.String)
			}
		case facilitytype.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ft.Description = value.String
			}
		case facilitytype.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field facility_type_children", value)
			} else if value.Valid {
				ft.facility_type_children = new(int)
				*ft.facility_type_children = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryParent queries the "parent" edge of the FacilityType entity.
func (ft *FacilityType) QueryParent() *FacilityTypeQuery {
	return (&FacilityTypeClient{config: ft.config}).QueryParent(ft)
}

// QueryChildren queries the "children" edge of the FacilityType entity.
func (ft *FacilityType) QueryChildren() *FacilityTypeQuery {
	return (&FacilityTypeClient{config: ft.config}).QueryChildren(ft)
}

// QueryChildFacilityTypes queries the "child_facility_types" edge of the FacilityType entity.
func (ft *FacilityType) QueryChildFacilityTypes() *FacilityTypeQuery {
	return (&FacilityTypeClient{config: ft.config}).QueryChildFacilityTypes(ft)
}

// Update returns a builder for updating this FacilityType.
// Note that you need to call FacilityType.Unwrap() before calling this method if this FacilityType
// was returned from a transaction, and the transaction was committed or rolled back.
func (ft *FacilityType) Update() *FacilityTypeUpdateOne {
	return (&FacilityTypeClient{config: ft.config}).UpdateOne(ft)
}

// Unwrap unwraps the FacilityType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ft *FacilityType) Unwrap() *FacilityType {
	tx, ok := ft.config.driver.(*txDriver)
	if !ok {
		panic("ent: FacilityType is not a transactional entity")
	}
	ft.config.driver = tx.drv
	return ft
}

// String implements the fmt.Stringer.
func (ft *FacilityType) String() string {
	var builder strings.Builder
	builder.WriteString("FacilityType(")
	builder.WriteString(fmt.Sprintf("id=%v", ft.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(ft.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(ft.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", string_ref=")
	builder.WriteString(ft.StringRef)
	builder.WriteString(", has_table=")
	builder.WriteString(fmt.Sprintf("%v", ft.HasTable))
	builder.WriteString(", description=")
	builder.WriteString(ft.Description)
	builder.WriteByte(')')
	return builder.String()
}

// FacilityTypes is a parsable slice of FacilityType.
type FacilityTypes []*FacilityType

func (ft FacilityTypes) config(cfg config) {
	for _i := range ft {
		ft[_i].config = cfg
	}
}
