// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/predicate"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/prodcatalogcategorytype"
)

// ProdCatalogCategoryTypeUpdate is the builder for updating ProdCatalogCategoryType entities.
type ProdCatalogCategoryTypeUpdate struct {
	config
	hooks    []Hook
	mutation *ProdCatalogCategoryTypeMutation
}

// Where adds a new predicate for the ProdCatalogCategoryTypeUpdate builder.
func (pcctu *ProdCatalogCategoryTypeUpdate) Where(ps ...predicate.ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.predicates = append(pcctu.mutation.predicates, ps...)
	return pcctu
}

// SetStringRef sets the "string_ref" field.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetStringRef(s string) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.SetStringRef(s)
	return pcctu
}

// SetNillableStringRef sets the "string_ref" field if the given value is not nil.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetNillableStringRef(s *string) *ProdCatalogCategoryTypeUpdate {
	if s != nil {
		pcctu.SetStringRef(*s)
	}
	return pcctu
}

// ClearStringRef clears the value of the "string_ref" field.
func (pcctu *ProdCatalogCategoryTypeUpdate) ClearStringRef() *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.ClearStringRef()
	return pcctu
}

// SetDescription sets the "description" field.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetDescription(s string) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.SetDescription(s)
	return pcctu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetNillableDescription(s *string) *ProdCatalogCategoryTypeUpdate {
	if s != nil {
		pcctu.SetDescription(*s)
	}
	return pcctu
}

// ClearDescription clears the value of the "description" field.
func (pcctu *ProdCatalogCategoryTypeUpdate) ClearDescription() *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.ClearDescription()
	return pcctu
}

// SetParentID sets the "parent" edge to the ProdCatalogCategoryType entity by ID.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetParentID(id int) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.SetParentID(id)
	return pcctu
}

// SetNillableParentID sets the "parent" edge to the ProdCatalogCategoryType entity by ID if the given value is not nil.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetNillableParentID(id *int) *ProdCatalogCategoryTypeUpdate {
	if id != nil {
		pcctu = pcctu.SetParentID(*id)
	}
	return pcctu
}

// SetParent sets the "parent" edge to the ProdCatalogCategoryType entity.
func (pcctu *ProdCatalogCategoryTypeUpdate) SetParent(p *ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdate {
	return pcctu.SetParentID(p.ID)
}

// AddChildIDs adds the "children" edge to the ProdCatalogCategoryType entity by IDs.
func (pcctu *ProdCatalogCategoryTypeUpdate) AddChildIDs(ids ...int) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.AddChildIDs(ids...)
	return pcctu
}

// AddChildren adds the "children" edges to the ProdCatalogCategoryType entity.
func (pcctu *ProdCatalogCategoryTypeUpdate) AddChildren(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctu.AddChildIDs(ids...)
}

// AddChildProdCatalogCategoryTypeIDs adds the "child_prod_catalog_category_types" edge to the ProdCatalogCategoryType entity by IDs.
func (pcctu *ProdCatalogCategoryTypeUpdate) AddChildProdCatalogCategoryTypeIDs(ids ...int) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.AddChildProdCatalogCategoryTypeIDs(ids...)
	return pcctu
}

// AddChildProdCatalogCategoryTypes adds the "child_prod_catalog_category_types" edges to the ProdCatalogCategoryType entity.
func (pcctu *ProdCatalogCategoryTypeUpdate) AddChildProdCatalogCategoryTypes(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctu.AddChildProdCatalogCategoryTypeIDs(ids...)
}

// Mutation returns the ProdCatalogCategoryTypeMutation object of the builder.
func (pcctu *ProdCatalogCategoryTypeUpdate) Mutation() *ProdCatalogCategoryTypeMutation {
	return pcctu.mutation
}

// ClearParent clears the "parent" edge to the ProdCatalogCategoryType entity.
func (pcctu *ProdCatalogCategoryTypeUpdate) ClearParent() *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.ClearParent()
	return pcctu
}

// ClearChildren clears all "children" edges to the ProdCatalogCategoryType entity.
func (pcctu *ProdCatalogCategoryTypeUpdate) ClearChildren() *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.ClearChildren()
	return pcctu
}

// RemoveChildIDs removes the "children" edge to ProdCatalogCategoryType entities by IDs.
func (pcctu *ProdCatalogCategoryTypeUpdate) RemoveChildIDs(ids ...int) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.RemoveChildIDs(ids...)
	return pcctu
}

// RemoveChildren removes "children" edges to ProdCatalogCategoryType entities.
func (pcctu *ProdCatalogCategoryTypeUpdate) RemoveChildren(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctu.RemoveChildIDs(ids...)
}

// ClearChildProdCatalogCategoryTypes clears all "child_prod_catalog_category_types" edges to the ProdCatalogCategoryType entity.
func (pcctu *ProdCatalogCategoryTypeUpdate) ClearChildProdCatalogCategoryTypes() *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.ClearChildProdCatalogCategoryTypes()
	return pcctu
}

// RemoveChildProdCatalogCategoryTypeIDs removes the "child_prod_catalog_category_types" edge to ProdCatalogCategoryType entities by IDs.
func (pcctu *ProdCatalogCategoryTypeUpdate) RemoveChildProdCatalogCategoryTypeIDs(ids ...int) *ProdCatalogCategoryTypeUpdate {
	pcctu.mutation.RemoveChildProdCatalogCategoryTypeIDs(ids...)
	return pcctu
}

// RemoveChildProdCatalogCategoryTypes removes "child_prod_catalog_category_types" edges to ProdCatalogCategoryType entities.
func (pcctu *ProdCatalogCategoryTypeUpdate) RemoveChildProdCatalogCategoryTypes(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctu.RemoveChildProdCatalogCategoryTypeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pcctu *ProdCatalogCategoryTypeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	pcctu.defaults()
	if len(pcctu.hooks) == 0 {
		affected, err = pcctu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProdCatalogCategoryTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcctu.mutation = mutation
			affected, err = pcctu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pcctu.hooks) - 1; i >= 0; i-- {
			mut = pcctu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcctu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pcctu *ProdCatalogCategoryTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := pcctu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pcctu *ProdCatalogCategoryTypeUpdate) Exec(ctx context.Context) error {
	_, err := pcctu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcctu *ProdCatalogCategoryTypeUpdate) ExecX(ctx context.Context) {
	if err := pcctu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcctu *ProdCatalogCategoryTypeUpdate) defaults() {
	if _, ok := pcctu.mutation.UpdateTime(); !ok {
		v := prodcatalogcategorytype.UpdateDefaultUpdateTime()
		pcctu.mutation.SetUpdateTime(v)
	}
}

func (pcctu *ProdCatalogCategoryTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   prodcatalogcategorytype.Table,
			Columns: prodcatalogcategorytype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prodcatalogcategorytype.FieldID,
			},
		},
	}
	if ps := pcctu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcctu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: prodcatalogcategorytype.FieldUpdateTime,
		})
	}
	if value, ok := pcctu.mutation.StringRef(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prodcatalogcategorytype.FieldStringRef,
		})
	}
	if pcctu.mutation.StringRefCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: prodcatalogcategorytype.FieldStringRef,
		})
	}
	if value, ok := pcctu.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prodcatalogcategorytype.FieldDescription,
		})
	}
	if pcctu.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: prodcatalogcategorytype.FieldDescription,
		})
	}
	if pcctu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prodcatalogcategorytype.ParentTable,
			Columns: []string{prodcatalogcategorytype.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctu.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prodcatalogcategorytype.ParentTable,
			Columns: []string{prodcatalogcategorytype.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pcctu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildrenTable,
			Columns: []string{prodcatalogcategorytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctu.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !pcctu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildrenTable,
			Columns: []string{prodcatalogcategorytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctu.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildrenTable,
			Columns: []string{prodcatalogcategorytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pcctu.mutation.ChildProdCatalogCategoryTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildProdCatalogCategoryTypesTable,
			Columns: prodcatalogcategorytype.ChildProdCatalogCategoryTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctu.mutation.RemovedChildProdCatalogCategoryTypesIDs(); len(nodes) > 0 && !pcctu.mutation.ChildProdCatalogCategoryTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildProdCatalogCategoryTypesTable,
			Columns: prodcatalogcategorytype.ChildProdCatalogCategoryTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctu.mutation.ChildProdCatalogCategoryTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildProdCatalogCategoryTypesTable,
			Columns: prodcatalogcategorytype.ChildProdCatalogCategoryTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pcctu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prodcatalogcategorytype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ProdCatalogCategoryTypeUpdateOne is the builder for updating a single ProdCatalogCategoryType entity.
type ProdCatalogCategoryTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProdCatalogCategoryTypeMutation
}

// SetStringRef sets the "string_ref" field.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetStringRef(s string) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.SetStringRef(s)
	return pcctuo
}

// SetNillableStringRef sets the "string_ref" field if the given value is not nil.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetNillableStringRef(s *string) *ProdCatalogCategoryTypeUpdateOne {
	if s != nil {
		pcctuo.SetStringRef(*s)
	}
	return pcctuo
}

// ClearStringRef clears the value of the "string_ref" field.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) ClearStringRef() *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.ClearStringRef()
	return pcctuo
}

// SetDescription sets the "description" field.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetDescription(s string) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.SetDescription(s)
	return pcctuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetNillableDescription(s *string) *ProdCatalogCategoryTypeUpdateOne {
	if s != nil {
		pcctuo.SetDescription(*s)
	}
	return pcctuo
}

// ClearDescription clears the value of the "description" field.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) ClearDescription() *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.ClearDescription()
	return pcctuo
}

// SetParentID sets the "parent" edge to the ProdCatalogCategoryType entity by ID.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetParentID(id int) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.SetParentID(id)
	return pcctuo
}

// SetNillableParentID sets the "parent" edge to the ProdCatalogCategoryType entity by ID if the given value is not nil.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetNillableParentID(id *int) *ProdCatalogCategoryTypeUpdateOne {
	if id != nil {
		pcctuo = pcctuo.SetParentID(*id)
	}
	return pcctuo
}

// SetParent sets the "parent" edge to the ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SetParent(p *ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdateOne {
	return pcctuo.SetParentID(p.ID)
}

// AddChildIDs adds the "children" edge to the ProdCatalogCategoryType entity by IDs.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) AddChildIDs(ids ...int) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.AddChildIDs(ids...)
	return pcctuo
}

// AddChildren adds the "children" edges to the ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) AddChildren(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctuo.AddChildIDs(ids...)
}

// AddChildProdCatalogCategoryTypeIDs adds the "child_prod_catalog_category_types" edge to the ProdCatalogCategoryType entity by IDs.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) AddChildProdCatalogCategoryTypeIDs(ids ...int) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.AddChildProdCatalogCategoryTypeIDs(ids...)
	return pcctuo
}

// AddChildProdCatalogCategoryTypes adds the "child_prod_catalog_category_types" edges to the ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) AddChildProdCatalogCategoryTypes(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctuo.AddChildProdCatalogCategoryTypeIDs(ids...)
}

// Mutation returns the ProdCatalogCategoryTypeMutation object of the builder.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) Mutation() *ProdCatalogCategoryTypeMutation {
	return pcctuo.mutation
}

// ClearParent clears the "parent" edge to the ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) ClearParent() *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.ClearParent()
	return pcctuo
}

// ClearChildren clears all "children" edges to the ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) ClearChildren() *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.ClearChildren()
	return pcctuo
}

// RemoveChildIDs removes the "children" edge to ProdCatalogCategoryType entities by IDs.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) RemoveChildIDs(ids ...int) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.RemoveChildIDs(ids...)
	return pcctuo
}

// RemoveChildren removes "children" edges to ProdCatalogCategoryType entities.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) RemoveChildren(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctuo.RemoveChildIDs(ids...)
}

// ClearChildProdCatalogCategoryTypes clears all "child_prod_catalog_category_types" edges to the ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) ClearChildProdCatalogCategoryTypes() *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.ClearChildProdCatalogCategoryTypes()
	return pcctuo
}

// RemoveChildProdCatalogCategoryTypeIDs removes the "child_prod_catalog_category_types" edge to ProdCatalogCategoryType entities by IDs.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) RemoveChildProdCatalogCategoryTypeIDs(ids ...int) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.mutation.RemoveChildProdCatalogCategoryTypeIDs(ids...)
	return pcctuo
}

// RemoveChildProdCatalogCategoryTypes removes "child_prod_catalog_category_types" edges to ProdCatalogCategoryType entities.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) RemoveChildProdCatalogCategoryTypes(p ...*ProdCatalogCategoryType) *ProdCatalogCategoryTypeUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcctuo.RemoveChildProdCatalogCategoryTypeIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) Select(field string, fields ...string) *ProdCatalogCategoryTypeUpdateOne {
	pcctuo.fields = append([]string{field}, fields...)
	return pcctuo
}

// Save executes the query and returns the updated ProdCatalogCategoryType entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) Save(ctx context.Context) (*ProdCatalogCategoryType, error) {
	var (
		err  error
		node *ProdCatalogCategoryType
	)
	pcctuo.defaults()
	if len(pcctuo.hooks) == 0 {
		node, err = pcctuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProdCatalogCategoryTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcctuo.mutation = mutation
			node, err = pcctuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pcctuo.hooks) - 1; i >= 0; i-- {
			mut = pcctuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcctuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) SaveX(ctx context.Context) *ProdCatalogCategoryType {
	node, err := pcctuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := pcctuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) ExecX(ctx context.Context) {
	if err := pcctuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcctuo *ProdCatalogCategoryTypeUpdateOne) defaults() {
	if _, ok := pcctuo.mutation.UpdateTime(); !ok {
		v := prodcatalogcategorytype.UpdateDefaultUpdateTime()
		pcctuo.mutation.SetUpdateTime(v)
	}
}

func (pcctuo *ProdCatalogCategoryTypeUpdateOne) sqlSave(ctx context.Context) (_node *ProdCatalogCategoryType, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   prodcatalogcategorytype.Table,
			Columns: prodcatalogcategorytype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: prodcatalogcategorytype.FieldID,
			},
		},
	}
	id, ok := pcctuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ProdCatalogCategoryType.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := pcctuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prodcatalogcategorytype.FieldID)
		for _, f := range fields {
			if !prodcatalogcategorytype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prodcatalogcategorytype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pcctuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcctuo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: prodcatalogcategorytype.FieldUpdateTime,
		})
	}
	if value, ok := pcctuo.mutation.StringRef(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prodcatalogcategorytype.FieldStringRef,
		})
	}
	if pcctuo.mutation.StringRefCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: prodcatalogcategorytype.FieldStringRef,
		})
	}
	if value, ok := pcctuo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: prodcatalogcategorytype.FieldDescription,
		})
	}
	if pcctuo.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: prodcatalogcategorytype.FieldDescription,
		})
	}
	if pcctuo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prodcatalogcategorytype.ParentTable,
			Columns: []string{prodcatalogcategorytype.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctuo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   prodcatalogcategorytype.ParentTable,
			Columns: []string{prodcatalogcategorytype.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pcctuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildrenTable,
			Columns: []string{prodcatalogcategorytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctuo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !pcctuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildrenTable,
			Columns: []string{prodcatalogcategorytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctuo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildrenTable,
			Columns: []string{prodcatalogcategorytype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pcctuo.mutation.ChildProdCatalogCategoryTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildProdCatalogCategoryTypesTable,
			Columns: prodcatalogcategorytype.ChildProdCatalogCategoryTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctuo.mutation.RemovedChildProdCatalogCategoryTypesIDs(); len(nodes) > 0 && !pcctuo.mutation.ChildProdCatalogCategoryTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildProdCatalogCategoryTypesTable,
			Columns: prodcatalogcategorytype.ChildProdCatalogCategoryTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pcctuo.mutation.ChildProdCatalogCategoryTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   prodcatalogcategorytype.ChildProdCatalogCategoryTypesTable,
			Columns: prodcatalogcategorytype.ChildProdCatalogCategoryTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: prodcatalogcategorytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProdCatalogCategoryType{config: pcctuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pcctuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prodcatalogcategorytype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
