// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/shipmentgatewayconfig"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/shipmentgatewayconfigtype"
)

// ShipmentGatewayConfigTypeCreate is the builder for creating a ShipmentGatewayConfigType entity.
type ShipmentGatewayConfigTypeCreate struct {
	config
	mutation *ShipmentGatewayConfigTypeMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetCreateTime(t time.Time) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.SetCreateTime(t)
	return sgctc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetNillableCreateTime(t *time.Time) *ShipmentGatewayConfigTypeCreate {
	if t != nil {
		sgctc.SetCreateTime(*t)
	}
	return sgctc
}

// SetUpdateTime sets the "update_time" field.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetUpdateTime(t time.Time) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.SetUpdateTime(t)
	return sgctc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetNillableUpdateTime(t *time.Time) *ShipmentGatewayConfigTypeCreate {
	if t != nil {
		sgctc.SetUpdateTime(*t)
	}
	return sgctc
}

// SetStringRef sets the "string_ref" field.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetStringRef(s string) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.SetStringRef(s)
	return sgctc
}

// SetNillableStringRef sets the "string_ref" field if the given value is not nil.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetNillableStringRef(s *string) *ShipmentGatewayConfigTypeCreate {
	if s != nil {
		sgctc.SetStringRef(*s)
	}
	return sgctc
}

// SetHasTable sets the "has_table" field.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetHasTable(st shipmentgatewayconfigtype.HasTable) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.SetHasTable(st)
	return sgctc
}

// SetNillableHasTable sets the "has_table" field if the given value is not nil.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetNillableHasTable(st *shipmentgatewayconfigtype.HasTable) *ShipmentGatewayConfigTypeCreate {
	if st != nil {
		sgctc.SetHasTable(*st)
	}
	return sgctc
}

// SetDescription sets the "description" field.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetDescription(s string) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.SetDescription(s)
	return sgctc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetNillableDescription(s *string) *ShipmentGatewayConfigTypeCreate {
	if s != nil {
		sgctc.SetDescription(*s)
	}
	return sgctc
}

// SetParentID sets the "parent" edge to the ShipmentGatewayConfigType entity by ID.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetParentID(id int) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.SetParentID(id)
	return sgctc
}

// SetNillableParentID sets the "parent" edge to the ShipmentGatewayConfigType entity by ID if the given value is not nil.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetNillableParentID(id *int) *ShipmentGatewayConfigTypeCreate {
	if id != nil {
		sgctc = sgctc.SetParentID(*id)
	}
	return sgctc
}

// SetParent sets the "parent" edge to the ShipmentGatewayConfigType entity.
func (sgctc *ShipmentGatewayConfigTypeCreate) SetParent(s *ShipmentGatewayConfigType) *ShipmentGatewayConfigTypeCreate {
	return sgctc.SetParentID(s.ID)
}

// AddChildIDs adds the "children" edge to the ShipmentGatewayConfigType entity by IDs.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddChildIDs(ids ...int) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.AddChildIDs(ids...)
	return sgctc
}

// AddChildren adds the "children" edges to the ShipmentGatewayConfigType entity.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddChildren(s ...*ShipmentGatewayConfigType) *ShipmentGatewayConfigTypeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sgctc.AddChildIDs(ids...)
}

// AddSiblingShipmentGatewayConfigTypeIDs adds the "sibling_shipment_gateway_config_types" edge to the ShipmentGatewayConfigType entity by IDs.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddSiblingShipmentGatewayConfigTypeIDs(ids ...int) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.AddSiblingShipmentGatewayConfigTypeIDs(ids...)
	return sgctc
}

// AddSiblingShipmentGatewayConfigTypes adds the "sibling_shipment_gateway_config_types" edges to the ShipmentGatewayConfigType entity.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddSiblingShipmentGatewayConfigTypes(s ...*ShipmentGatewayConfigType) *ShipmentGatewayConfigTypeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sgctc.AddSiblingShipmentGatewayConfigTypeIDs(ids...)
}

// AddShipmentGatewayConfigIDs adds the "shipment_gateway_configs" edge to the ShipmentGatewayConfig entity by IDs.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddShipmentGatewayConfigIDs(ids ...int) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.AddShipmentGatewayConfigIDs(ids...)
	return sgctc
}

// AddShipmentGatewayConfigs adds the "shipment_gateway_configs" edges to the ShipmentGatewayConfig entity.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddShipmentGatewayConfigs(s ...*ShipmentGatewayConfig) *ShipmentGatewayConfigTypeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sgctc.AddShipmentGatewayConfigIDs(ids...)
}

// AddChildShipmentGatewayConfigTypeIDs adds the "child_shipment_gateway_config_types" edge to the ShipmentGatewayConfigType entity by IDs.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddChildShipmentGatewayConfigTypeIDs(ids ...int) *ShipmentGatewayConfigTypeCreate {
	sgctc.mutation.AddChildShipmentGatewayConfigTypeIDs(ids...)
	return sgctc
}

// AddChildShipmentGatewayConfigTypes adds the "child_shipment_gateway_config_types" edges to the ShipmentGatewayConfigType entity.
func (sgctc *ShipmentGatewayConfigTypeCreate) AddChildShipmentGatewayConfigTypes(s ...*ShipmentGatewayConfigType) *ShipmentGatewayConfigTypeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sgctc.AddChildShipmentGatewayConfigTypeIDs(ids...)
}

// Mutation returns the ShipmentGatewayConfigTypeMutation object of the builder.
func (sgctc *ShipmentGatewayConfigTypeCreate) Mutation() *ShipmentGatewayConfigTypeMutation {
	return sgctc.mutation
}

// Save creates the ShipmentGatewayConfigType in the database.
func (sgctc *ShipmentGatewayConfigTypeCreate) Save(ctx context.Context) (*ShipmentGatewayConfigType, error) {
	var (
		err  error
		node *ShipmentGatewayConfigType
	)
	sgctc.defaults()
	if len(sgctc.hooks) == 0 {
		if err = sgctc.check(); err != nil {
			return nil, err
		}
		node, err = sgctc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShipmentGatewayConfigTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sgctc.check(); err != nil {
				return nil, err
			}
			sgctc.mutation = mutation
			if node, err = sgctc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sgctc.hooks) - 1; i >= 0; i-- {
			mut = sgctc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sgctc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sgctc *ShipmentGatewayConfigTypeCreate) SaveX(ctx context.Context) *ShipmentGatewayConfigType {
	v, err := sgctc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (sgctc *ShipmentGatewayConfigTypeCreate) defaults() {
	if _, ok := sgctc.mutation.CreateTime(); !ok {
		v := shipmentgatewayconfigtype.DefaultCreateTime()
		sgctc.mutation.SetCreateTime(v)
	}
	if _, ok := sgctc.mutation.UpdateTime(); !ok {
		v := shipmentgatewayconfigtype.DefaultUpdateTime()
		sgctc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sgctc *ShipmentGatewayConfigTypeCreate) check() error {
	if _, ok := sgctc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := sgctc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if v, ok := sgctc.mutation.HasTable(); ok {
		if err := shipmentgatewayconfigtype.HasTableValidator(v); err != nil {
			return &ValidationError{Name: "has_table", err: fmt.Errorf("ent: validator failed for field \"has_table\": %w", err)}
		}
	}
	return nil
}

func (sgctc *ShipmentGatewayConfigTypeCreate) sqlSave(ctx context.Context) (*ShipmentGatewayConfigType, error) {
	_node, _spec := sgctc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sgctc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sgctc *ShipmentGatewayConfigTypeCreate) createSpec() (*ShipmentGatewayConfigType, *sqlgraph.CreateSpec) {
	var (
		_node = &ShipmentGatewayConfigType{config: sgctc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: shipmentgatewayconfigtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shipmentgatewayconfigtype.FieldID,
			},
		}
	)
	if value, ok := sgctc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shipmentgatewayconfigtype.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := sgctc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shipmentgatewayconfigtype.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := sgctc.mutation.StringRef(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shipmentgatewayconfigtype.FieldStringRef,
		})
		_node.StringRef = value
	}
	if value, ok := sgctc.mutation.HasTable(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: shipmentgatewayconfigtype.FieldHasTable,
		})
		_node.HasTable = value
	}
	if value, ok := sgctc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shipmentgatewayconfigtype.FieldDescription,
		})
		_node.Description = value
	}
	if nodes := sgctc.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shipmentgatewayconfigtype.ParentTable,
			Columns: []string{shipmentgatewayconfigtype.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shipmentgatewayconfigtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.shipment_gateway_config_type_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sgctc.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipmentgatewayconfigtype.ChildrenTable,
			Columns: []string{shipmentgatewayconfigtype.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shipmentgatewayconfigtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sgctc.mutation.SiblingShipmentGatewayConfigTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   shipmentgatewayconfigtype.SiblingShipmentGatewayConfigTypesTable,
			Columns: shipmentgatewayconfigtype.SiblingShipmentGatewayConfigTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shipmentgatewayconfigtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sgctc.mutation.ShipmentGatewayConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipmentgatewayconfigtype.ShipmentGatewayConfigsTable,
			Columns: []string{shipmentgatewayconfigtype.ShipmentGatewayConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shipmentgatewayconfig.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sgctc.mutation.ChildShipmentGatewayConfigTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   shipmentgatewayconfigtype.ChildShipmentGatewayConfigTypesTable,
			Columns: shipmentgatewayconfigtype.ChildShipmentGatewayConfigTypesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shipmentgatewayconfigtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShipmentGatewayConfigTypeCreateBulk is the builder for creating many ShipmentGatewayConfigType entities in bulk.
type ShipmentGatewayConfigTypeCreateBulk struct {
	config
	builders []*ShipmentGatewayConfigTypeCreate
}

// Save creates the ShipmentGatewayConfigType entities in the database.
func (sgctcb *ShipmentGatewayConfigTypeCreateBulk) Save(ctx context.Context) ([]*ShipmentGatewayConfigType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(sgctcb.builders))
	nodes := make([]*ShipmentGatewayConfigType, len(sgctcb.builders))
	mutators := make([]Mutator, len(sgctcb.builders))
	for i := range sgctcb.builders {
		func(i int, root context.Context) {
			builder := sgctcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShipmentGatewayConfigTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sgctcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sgctcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sgctcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sgctcb *ShipmentGatewayConfigTypeCreateBulk) SaveX(ctx context.Context) []*ShipmentGatewayConfigType {
	v, err := sgctcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
