// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/predicate"
	"github.com/samlet/petrel/alfin/modules/catalog/ent/variancereason"
)

// VarianceReasonQuery is the builder for querying VarianceReason entities.
type VarianceReasonQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VarianceReason
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VarianceReasonQuery builder.
func (vrq *VarianceReasonQuery) Where(ps ...predicate.VarianceReason) *VarianceReasonQuery {
	vrq.predicates = append(vrq.predicates, ps...)
	return vrq
}

// Limit adds a limit step to the query.
func (vrq *VarianceReasonQuery) Limit(limit int) *VarianceReasonQuery {
	vrq.limit = &limit
	return vrq
}

// Offset adds an offset step to the query.
func (vrq *VarianceReasonQuery) Offset(offset int) *VarianceReasonQuery {
	vrq.offset = &offset
	return vrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vrq *VarianceReasonQuery) Unique(unique bool) *VarianceReasonQuery {
	vrq.unique = &unique
	return vrq
}

// Order adds an order step to the query.
func (vrq *VarianceReasonQuery) Order(o ...OrderFunc) *VarianceReasonQuery {
	vrq.order = append(vrq.order, o...)
	return vrq
}

// First returns the first VarianceReason entity from the query.
// Returns a *NotFoundError when no VarianceReason was found.
func (vrq *VarianceReasonQuery) First(ctx context.Context) (*VarianceReason, error) {
	nodes, err := vrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{variancereason.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vrq *VarianceReasonQuery) FirstX(ctx context.Context) *VarianceReason {
	node, err := vrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VarianceReason ID from the query.
// Returns a *NotFoundError when no VarianceReason ID was found.
func (vrq *VarianceReasonQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{variancereason.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vrq *VarianceReasonQuery) FirstIDX(ctx context.Context) int {
	id, err := vrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VarianceReason entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one VarianceReason entity is not found.
// Returns a *NotFoundError when no VarianceReason entities are found.
func (vrq *VarianceReasonQuery) Only(ctx context.Context) (*VarianceReason, error) {
	nodes, err := vrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{variancereason.Label}
	default:
		return nil, &NotSingularError{variancereason.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vrq *VarianceReasonQuery) OnlyX(ctx context.Context) *VarianceReason {
	node, err := vrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VarianceReason ID in the query.
// Returns a *NotSingularError when exactly one VarianceReason ID is not found.
// Returns a *NotFoundError when no entities are found.
func (vrq *VarianceReasonQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = &NotSingularError{variancereason.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vrq *VarianceReasonQuery) OnlyIDX(ctx context.Context) int {
	id, err := vrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VarianceReasons.
func (vrq *VarianceReasonQuery) All(ctx context.Context) ([]*VarianceReason, error) {
	if err := vrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vrq *VarianceReasonQuery) AllX(ctx context.Context) []*VarianceReason {
	nodes, err := vrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VarianceReason IDs.
func (vrq *VarianceReasonQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := vrq.Select(variancereason.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vrq *VarianceReasonQuery) IDsX(ctx context.Context) []int {
	ids, err := vrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vrq *VarianceReasonQuery) Count(ctx context.Context) (int, error) {
	if err := vrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vrq *VarianceReasonQuery) CountX(ctx context.Context) int {
	count, err := vrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vrq *VarianceReasonQuery) Exist(ctx context.Context) (bool, error) {
	if err := vrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vrq *VarianceReasonQuery) ExistX(ctx context.Context) bool {
	exist, err := vrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VarianceReasonQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vrq *VarianceReasonQuery) Clone() *VarianceReasonQuery {
	if vrq == nil {
		return nil
	}
	return &VarianceReasonQuery{
		config:     vrq.config,
		limit:      vrq.limit,
		offset:     vrq.offset,
		order:      append([]OrderFunc{}, vrq.order...),
		predicates: append([]predicate.VarianceReason{}, vrq.predicates...),
		// clone intermediate query.
		sql:  vrq.sql.Clone(),
		path: vrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VarianceReason.Query().
//		GroupBy(variancereason.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (vrq *VarianceReasonQuery) GroupBy(field string, fields ...string) *VarianceReasonGroupBy {
	group := &VarianceReasonGroupBy{config: vrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.VarianceReason.Query().
//		Select(variancereason.FieldCreateTime).
//		Scan(ctx, &v)
//
func (vrq *VarianceReasonQuery) Select(field string, fields ...string) *VarianceReasonSelect {
	vrq.fields = append([]string{field}, fields...)
	return &VarianceReasonSelect{VarianceReasonQuery: vrq}
}

func (vrq *VarianceReasonQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vrq.fields {
		if !variancereason.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vrq.path != nil {
		prev, err := vrq.path(ctx)
		if err != nil {
			return err
		}
		vrq.sql = prev
	}
	return nil
}

func (vrq *VarianceReasonQuery) sqlAll(ctx context.Context) ([]*VarianceReason, error) {
	var (
		nodes = []*VarianceReason{}
		_spec = vrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &VarianceReason{config: vrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, vrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vrq *VarianceReasonQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vrq.querySpec()
	return sqlgraph.CountNodes(ctx, vrq.driver, _spec)
}

func (vrq *VarianceReasonQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := vrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (vrq *VarianceReasonQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   variancereason.Table,
			Columns: variancereason.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: variancereason.FieldID,
			},
		},
		From:   vrq.sql,
		Unique: true,
	}
	if unique := vrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, variancereason.FieldID)
		for i := range fields {
			if fields[i] != variancereason.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vrq *VarianceReasonQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vrq.driver.Dialect())
	t1 := builder.Table(variancereason.Table)
	columns := vrq.fields
	if len(columns) == 0 {
		columns = variancereason.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vrq.sql != nil {
		selector = vrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range vrq.predicates {
		p(selector)
	}
	for _, p := range vrq.order {
		p(selector)
	}
	if offset := vrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VarianceReasonGroupBy is the group-by builder for VarianceReason entities.
type VarianceReasonGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vrgb *VarianceReasonGroupBy) Aggregate(fns ...AggregateFunc) *VarianceReasonGroupBy {
	vrgb.fns = append(vrgb.fns, fns...)
	return vrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vrgb *VarianceReasonGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vrgb.path(ctx)
	if err != nil {
		return err
	}
	vrgb.sql = query
	return vrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vrgb.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) StringsX(ctx context.Context) []string {
	v, err := vrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) StringX(ctx context.Context) string {
	v, err := vrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vrgb.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) IntsX(ctx context.Context) []int {
	v, err := vrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) IntX(ctx context.Context) int {
	v, err := vrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vrgb.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vrgb.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vrgb *VarianceReasonGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vrgb *VarianceReasonGroupBy) BoolX(ctx context.Context) bool {
	v, err := vrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vrgb *VarianceReasonGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vrgb.fields {
		if !variancereason.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vrgb *VarianceReasonGroupBy) sqlQuery() *sql.Selector {
	selector := vrgb.sql.Select()
	aggregation := make([]string, 0, len(vrgb.fns))
	for _, fn := range vrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vrgb.fields)+len(vrgb.fns))
		for _, f := range vrgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vrgb.fields...)...)
}

// VarianceReasonSelect is the builder for selecting fields of VarianceReason entities.
type VarianceReasonSelect struct {
	*VarianceReasonQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vrs *VarianceReasonSelect) Scan(ctx context.Context, v interface{}) error {
	if err := vrs.prepareQuery(ctx); err != nil {
		return err
	}
	vrs.sql = vrs.VarianceReasonQuery.sqlQuery(ctx)
	return vrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vrs *VarianceReasonSelect) ScanX(ctx context.Context, v interface{}) {
	if err := vrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Strings(ctx context.Context) ([]string, error) {
	if len(vrs.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := vrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vrs *VarianceReasonSelect) StringsX(ctx context.Context) []string {
	v, err := vrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vrs *VarianceReasonSelect) StringX(ctx context.Context) string {
	v, err := vrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Ints(ctx context.Context) ([]int, error) {
	if len(vrs.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := vrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vrs *VarianceReasonSelect) IntsX(ctx context.Context) []int {
	v, err := vrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vrs *VarianceReasonSelect) IntX(ctx context.Context) int {
	v, err := vrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(vrs.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := vrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vrs *VarianceReasonSelect) Float64sX(ctx context.Context) []float64 {
	v, err := vrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vrs *VarianceReasonSelect) Float64X(ctx context.Context) float64 {
	v, err := vrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(vrs.fields) > 1 {
		return nil, errors.New("ent: VarianceReasonSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := vrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vrs *VarianceReasonSelect) BoolsX(ctx context.Context) []bool {
	v, err := vrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (vrs *VarianceReasonSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{variancereason.Label}
	default:
		err = fmt.Errorf("ent: VarianceReasonSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vrs *VarianceReasonSelect) BoolX(ctx context.Context) bool {
	v, err := vrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vrs *VarianceReasonSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := vrs.sql.Query()
	if err := vrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
