edges:
- name: WorkEffortSkillStandard
  relations:
  - rel: WorkEffort
    type: one
  - rel: SkillType
    type: one
- name: UserLoginSecurityGroup
  relations:
  - rel: UserLogin
    type: one
  - rel: SecurityGroup
    type: one
  - rel: SecurityGroupPermission
    type: many
- name: TemporalExpression
  relations:
  - rel: TemporalExpressionAssoc
    type: many
  - rel: TemporalExpressionAssoc
    type: many
  - rel: WorkEffort
    type: many
- name: SecurityGroup
  relations:
  - rel: SecurityGroupPermission
    type: many
  - rel: UserLoginSecurityGroup
    type: many
- name: SkillType
  relations:
  - rel: SkillType
    type: one
  - rel: SkillType
    type: many
  - rel: WorkEffortSkillStandard
    type: many
- name: TemporalExpressionAssoc
  relations:
  - rel: TemporalExpression
    type: one
  - rel: TemporalExpression
    type: one
- name: StatusItem
  relations:
  - rel: StatusType
    type: one
  - rel: Party
    type: many
  - rel: PartyStatus
    type: many
  - rel: StatusValidChange
    type: many
  - rel: StatusValidChange
    type: many
  - rel: WorkEffort
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: WorkEffortAssoc
  relations:
  - rel: WorkEffort
    type: one
  - rel: WorkEffort
    type: one
- name: PartyContactMech
  relations:
  - rel: Party
    type: one
  - rel: Person
    type: one-nofk
  - rel: PartyRole
    type: one
  - rel: RoleType
    type: one
- name: FixedAsset
  relations:
  - rel: FixedAsset
    type: one
  - rel: Party
    type: one
  - rel: RoleType
    type: one
  - rel: PartyRole
    type: one-nofk
  - rel: FixedAsset
    type: many
  - rel: WorkEffort
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
- name: PartyRole
  relations:
  - rel: Party
    type: one
  - rel: RoleType
    type: one
  - rel: FixedAsset
    type: many
  - rel: PartyContactMech
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: WorkEffortFixedAssetAssign
  relations:
  - rel: WorkEffort
    type: one
  - rel: FixedAsset
    type: one
  - rel: StatusItem
    type: one
  - rel: StatusItem
    type: one
- name: SecurityGroupPermission
  relations:
  - rel: SecurityGroup
    type: one
- name: Party
  relations:
  - rel: UserLogin
    type: one
  - rel: UserLogin
    type: one
  - rel: StatusItem
    type: one
  - rel: FixedAsset
    type: many
  - rel: PartyContactMech
    type: many
  - rel: PartyRole
    type: many
  - rel: PartyStatus
    type: many
  - rel: Person
    type: one-nofk
  - rel: UserLogin
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: StatusType
  relations:
  - rel: StatusType
    type: one
  - rel: StatusItem
    type: many
  - rel: StatusType
    type: many
- name: StatusValidChange
  relations:
  - rel: StatusItem
    type: one
  - rel: StatusItem
    type: one
- name: UserLogin
  relations:
  - rel: Party
    type: one
  - rel: Person
    type: one-nofk
  - rel: Party
    type: many
  - rel: Party
    type: many
  - rel: PartyStatus
    type: many
  - rel: UserLoginSecurityGroup
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: WorkEffort
  relations:
  - rel: WorkEffortType
    type: one
  - rel: WorkEffort
    type: one
  - rel: StatusItem
    type: one
  - rel: FixedAsset
    type: one
  - rel: TemporalExpression
    type: one
  - rel: WorkEffort
    type: many
  - rel: WorkEffortAssoc
    type: many
  - rel: WorkEffortAssoc
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
  - rel: WorkEffortSkillStandard
    type: many
- name: Person
  relations:
  - rel: Party
    type: one
  - rel: PartyContactMech
    type: many
  - rel: UserLogin
    type: many
- name: PartyStatus
  relations:
  - rel: StatusItem
    type: one
  - rel: Party
    type: one
  - rel: UserLogin
    type: one
- name: WorkEffortPartyAssignment
  relations:
  - rel: WorkEffort
    type: one
  - rel: Party
    type: one-nofk
  - rel: PartyRole
    type: one
  - rel: RoleType
    type: one-nofk
  - rel: UserLogin
    type: one
  - rel: StatusItem
    type: one
  - rel: StatusItem
    type: one
- name: RoleType
  relations:
  - rel: RoleType
    type: one
  - rel: FixedAsset
    type: many
  - rel: PartyContactMech
    type: many
  - rel: PartyRole
    type: many
  - rel: RoleType
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: WorkEffortType
  relations:
  - rel: WorkEffortType
    type: one
  - rel: WorkEffort
    type: many
  - rel: WorkEffortType
    type: many
entities:
  FixedAsset: fixedasset.json
  Party: party.json
  PartyContactMech: partycontactmech.json
  PartyRole: partyrole.json
  PartyStatus: partystatus.json
  Person: person.json
  RoleType: roletype.json
  SecurityGroup: securitygroup.json
  SecurityGroupPermission: securitygrouppermission.json
  SkillType: skilltype.json
  StatusItem: statusitem.json
  StatusType: statustype.json
  StatusValidChange: statusvalidchange.json
  TemporalExpression: temporalexpression.json
  TemporalExpressionAssoc: temporalexpressionassoc.json
  UserLogin: userlogin.json
  UserLoginSecurityGroup: userloginsecuritygroup.json
  WorkEffort: workeffort.json
  WorkEffortAssoc: workeffortassoc.json
  WorkEffortFixedAssetAssign: workeffortfixedassetassign.json
  WorkEffortPartyAssignment: workeffortpartyassignment.json
  WorkEffortSkillStandard: workeffortskillstandard.json
  WorkEffortType: workefforttype.json
name: workeffort
package: workeffort
total: 23
