edges:
- name: CommunicationEventType
  relations:
  - rel: CommunicationEventType
    type: one
  - rel: ContactMechType
    type: one
  - rel: CommunicationEventType
    type: many
- name: UserLoginSecurityGroup
  relations:
  - rel: UserLogin
    type: one
  - rel: SecurityGroup
    type: one
  - rel: SecurityGroupPermission
    type: many
- name: UserPreference
  relations:
  - rel: UserLogin
    type: one-nofk
- name: ContactMechTypePurpose
  relations:
  - rel: ContactMechType
    type: one
  - rel: ContactMechPurposeType
    type: one
- name: ContactMechType
  relations:
  - rel: ContactMechType
    type: one
  - rel: CommunicationEventType
    type: many
  - rel: ContactMechType
    type: many
  - rel: ContactMechTypePurpose
    type: many
- name: Person
  relations:
  - rel: Party
    type: one
  - rel: Enumeration
    type: one
  - rel: Enumeration
    type: one
  - rel: Enumeration
    type: one
  - rel: PartyContactMech
    type: many
  - rel: UserLogin
    type: many
- name: WorkEffortSkillStandard
  relations:
  - rel: WorkEffort
    type: one
  - rel: SkillType
    type: one
- name: PartyContactMech
  relations:
  - rel: Party
    type: one
  - rel: Person
    type: one-nofk
  - rel: PartyRole
    type: one
  - rel: RoleType
    type: one
- name: CommunicationEventPrpTyp
  relations:
  - rel: CommunicationEventPrpTyp
    type: one
  - rel: CommunicationEventPrpTyp
    type: many
- name: PartyType
  relations:
  - rel: PartyType
    type: one
  - rel: PartyType
    type: many
  - rel: Party
    type: many
  - rel: PartyType
    type: many
- name: WorkEffortPartyAssignment
  relations:
  - rel: WorkEffort
    type: one
  - rel: Party
    type: one-nofk
  - rel: PartyRole
    type: one
  - rel: RoleType
    type: one-nofk
  - rel: UserLogin
    type: one
  - rel: StatusItem
    type: one
  - rel: Enumeration
    type: one
  - rel: Enumeration
    type: one
  - rel: StatusItem
    type: one
- name: Party
  relations:
  - rel: PartyType
    type: one
  - rel: UserLogin
    type: one
  - rel: UserLogin
    type: one
  - rel: StatusItem
    type: one
  - rel: FixedAsset
    type: many
  - rel: PartyContactMech
    type: many
  - rel: PartyRole
    type: many
  - rel: PartyStatus
    type: many
  - rel: Person
    type: one-nofk
  - rel: UserLogin
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: WorkEffortType
  relations:
  - rel: WorkEffortType
    type: one
  - rel: WorkEffort
    type: many
  - rel: WorkEffortType
    type: many
- name: PartyClassificationType
  relations:
  - rel: PartyClassificationType
    type: one
  - rel: PartyClassificationType
    type: many
- name: PartyContentType
  relations:
  - rel: PartyContentType
    type: one
  - rel: PartyContentType
    type: many
- name: Enumeration
  relations:
  - rel: EnumerationType
    type: one
  - rel: FixedAsset
    type: many
  - rel: Person
    type: many
  - rel: Person
    type: many
  - rel: Person
    type: many
  - rel: WorkEffort
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: FixedAsset
  relations:
  - rel: FixedAsset
    type: one
  - rel: Enumeration
    type: one
  - rel: Party
    type: one
  - rel: RoleType
    type: one
  - rel: PartyRole
    type: one-nofk
  - rel: FixedAsset
    type: many
  - rel: WorkEffort
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
- name: EnumerationType
  relations:
  - rel: EnumerationType
    type: one
  - rel: Enumeration
    type: many
  - rel: EnumerationType
    type: many
- name: PartyStatus
  relations:
  - rel: StatusItem
    type: one
  - rel: Party
    type: one
  - rel: UserLogin
    type: one
- name: PartyRole
  relations:
  - rel: Party
    type: one
  - rel: RoleType
    type: one
  - rel: FixedAsset
    type: many
  - rel: PartyContactMech
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: SecurityGroup
  relations:
  - rel: SecurityGroupPermission
    type: many
  - rel: UserLoginSecurityGroup
    type: many
- name: SkillType
  relations:
  - rel: SkillType
    type: one
  - rel: SkillType
    type: many
  - rel: WorkEffortSkillStandard
    type: many
- name: UserLogin
  relations:
  - rel: Party
    type: one
  - rel: Person
    type: one-nofk
  - rel: Party
    type: many
  - rel: Party
    type: many
  - rel: PartyStatus
    type: many
  - rel: UserLoginSecurityGroup
    type: many
  - rel: UserPreference
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: WorkEffortAssoc
  relations:
  - rel: WorkEffort
    type: one
  - rel: WorkEffort
    type: one
- name: PartyRelationshipType
  relations:
  - rel: PartyRelationshipType
    type: one
  - rel: RoleType
    type: one
  - rel: RoleType
    type: one
  - rel: PartyRelationshipType
    type: many
- name: PartyQualType
  relations:
  - rel: PartyQualType
    type: one
  - rel: PartyQualType
    type: many
- name: StatusType
  relations:
  - rel: StatusType
    type: one
  - rel: StatusItem
    type: many
  - rel: StatusType
    type: many
- name: WorkEffortFixedAssetAssign
  relations:
  - rel: WorkEffort
    type: one
  - rel: FixedAsset
    type: one
  - rel: StatusItem
    type: one
  - rel: StatusItem
    type: one
- name: PartyIdentificationType
  relations:
  - rel: PartyIdentificationType
    type: one
  - rel: PartyIdentificationType
    type: many
- name: TemporalExpression
  relations:
  - rel: TemporalExpressionAssoc
    type: many
  - rel: TemporalExpressionAssoc
    type: many
  - rel: WorkEffort
    type: many
- name: TemporalExpressionAssoc
  relations:
  - rel: TemporalExpression
    type: one
  - rel: TemporalExpression
    type: one
- name: TermType
  relations:
  - rel: TermType
    type: one
  - rel: TermType
    type: many
- name: WorkEffort
  relations:
  - rel: WorkEffortType
    type: one
  - rel: WorkEffort
    type: one
  - rel: StatusItem
    type: one
  - rel: Enumeration
    type: one
  - rel: FixedAsset
    type: one
  - rel: TemporalExpression
    type: one
  - rel: WorkEffort
    type: many
  - rel: WorkEffortAssoc
    type: many
  - rel: WorkEffortAssoc
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
  - rel: WorkEffortSkillStandard
    type: many
- name: SecurityGroupPermission
  relations:
  - rel: SecurityGroup
    type: one
  - rel: SecurityPermission
    type: one-nofk
- name: ContactMechPurposeType
  relations:
  - rel: ContactMechTypePurpose
    type: many
- name: SecurityPermission
  relations:
  - rel: SecurityGroupPermission
    type: many
- name: RoleType
  relations:
  - rel: RoleType
    type: one
  - rel: FixedAsset
    type: many
  - rel: PartyContactMech
    type: many
  - rel: PartyRelationshipType
    type: many
  - rel: PartyRelationshipType
    type: many
  - rel: PartyRole
    type: many
  - rel: RoleType
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
- name: StatusValidChange
  relations:
  - rel: StatusItem
    type: one
  - rel: StatusItem
    type: one
- name: StatusItem
  relations:
  - rel: StatusType
    type: one
  - rel: Party
    type: many
  - rel: PartyStatus
    type: many
  - rel: StatusValidChange
    type: many
  - rel: StatusValidChange
    type: many
  - rel: WorkEffort
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
  - rel: WorkEffortFixedAssetAssign
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
  - rel: WorkEffortPartyAssignment
    type: many
entities:
  CommunicationEventPrpTyp: communicationeventprptyp.json
  CommunicationEventType: communicationeventtype.json
  ContactMechPurposeType: contactmechpurposetype.json
  ContactMechType: contactmechtype.json
  ContactMechTypePurpose: contactmechtypepurpose.json
  Enumeration: enumeration.json
  EnumerationType: enumerationtype.json
  FixedAsset: fixedasset.json
  Party: party.json
  PartyClassificationType: partyclassificationtype.json
  PartyContactMech: partycontactmech.json
  PartyContentType: partycontenttype.json
  PartyIdentificationType: partyidentificationtype.json
  PartyQualType: partyqualtype.json
  PartyRelationshipType: partyrelationshiptype.json
  PartyRole: partyrole.json
  PartyStatus: partystatus.json
  PartyType: partytype.json
  Person: person.json
  RoleType: roletype.json
  SecurityGroup: securitygroup.json
  SecurityGroupPermission: securitygrouppermission.json
  SecurityPermission: securitypermission.json
  SkillType: skilltype.json
  StatusItem: statusitem.json
  StatusType: statustype.json
  StatusValidChange: statusvalidchange.json
  TemporalExpression: temporalexpression.json
  TemporalExpressionAssoc: temporalexpressionassoc.json
  TermType: termtype.json
  UserLogin: userlogin.json
  UserLoginSecurityGroup: userloginsecuritygroup.json
  UserPreference: userpreference.json
  WorkEffort: workeffort.json
  WorkEffortAssoc: workeffortassoc.json
  WorkEffortFixedAssetAssign: workeffortfixedassetassign.json
  WorkEffortPartyAssignment: workeffortpartyassignment.json
  WorkEffortSkillStandard: workeffortskillstandard.json
  WorkEffortType: workefforttype.json
name: workeffort
package: workeffort
total: 39
